### ISSUE TITLE
TcpActor doesn't support message CheckTimeout(TcpCheck(CheckBase(...)))

### ISSUE THREAD

**Issue by snripa** [scalecube/gatling-tcp-extensions#8]
After running gatling script using tcp check, exceptions start looping continuously:
[ERROR] [02/03/2016 17:22:00.894] [GatlingSystem-akka.actor.default-dispatcher-4] [akka://GatlingSystem/user/tcpConnect-9/tcpActor-41] Actor io.gatling.tcp.TcpActor@2ea76e06 doesn't support message CheckTimeout(TcpCheck(CheckBase(<function1>,<function1>,<function1>,None),3000 milliseconds,1454512917873))
java.lang.IllegalArgumentException: Actor io.gatling.tcp.TcpActor@2ea76e06 doesn't support message CheckTimeout(TcpCheck(CheckBase(<function1>,<function1>,<function1>,None),3000 milliseconds,1454512917873))
	at io.gatling.core.akka.BaseActor.unhandled(BaseActor.scala:32)
	at akka.actor.Actor$$anonfun$aroundReceive$1.apply(Actor.scala:467)
	at akka.actor.Actor$$anonfun$aroundReceive$1.apply(Actor.scala:467)
	at io.gatling.tcp.TcpActor$$anonfun$disconnectedState$1.applyOrElse(TcpActor.scala:125)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at io.gatling.core.akka.BaseActor.aroundReceive(BaseActor.scala:22)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by myroslavlisniak** [comment]
Fixed, will be in next release
